# Generated by Django 2.1.5 on 2019-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0003_auto_20190316_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.TextField(),
        ),
    ]
