# Generated by Django 2.1.5 on 2019-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0005_auto_20190316_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
