# Generated by Django 2.1.5 on 2019-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0006_auto_20190316_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.ImageField(upload_to='img'),
        ),
    ]
