# Generated by Django 2.1.5 on 2019-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0007_auto_20190317_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='cleavage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_habit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_symmetry',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='diaphaneity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='formula',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='luster',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='mohs_scale_hardness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='optical_properties',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='refractive_index',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='specific_gravity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='streak',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='strunz_classification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='unit_cell',
            field=models.TextField(blank=True),
        ),
    ]
