# Generated by Django 2.1.5 on 2019-03-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0008_auto_20190318_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineral',
            name='image_filename',
        ),
    ]
